# creating array numpy

1. 1 se 10 tak ka NumPy array banao.

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2️⃣ Ek 1D array banao jisme values ho: 5, 10, 15, 20

In [4]:
arr = np.array([5,10,15,20])
arr

array([ 5, 10, 15, 20])

3️⃣ 3×3 ka zeros matrix banao.

In [5]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


4️⃣ 2×4 ka ones matrix banao.
- ones(rows, columns)

In [6]:
ar = np.ones((2, 4))
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

0 se 1 ke beech 5 equal values ka array banao.
- np.linspace(start, stop, number_of_values)

In [7]:
arr = np.linspace(0, 1, 5)
arr 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6️⃣ 10 se 50 tak ka array banao step size 5 ke sath.
- hint:- arange(start, stop, step)

In [10]:
arr = np.arange(10, 51, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

7️⃣ 4×4 identity matrix banao.

In [12]:
arr = np.eye(4, dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

8️⃣ 2D array banao:

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

9️⃣ Ek array banao jisme 10 elements ho aur sabki value 7 ho.

In [ ]:
arr = np.full((10),7)
arr

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

🔟 0 se 20 tak even numbers ka array banao.

In [22]:
arr = np.arange(0, 21, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

1️⃣1️⃣ 0 se 20 tak Odd numbers ka array banao.

In [25]:
arr = np.arange(1, 21, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# 🟢 Basic Level
1️⃣ Create a NumPy array with elements: 2, 4, 6, 8, 10.

2️⃣ Create an array from a Python tuple (1, 3, 5, 7).

3️⃣ Create a 5×5 matrix of zeros.

4️⃣ Create a 3×2 matrix of ones.

5️⃣ Create an array from 0 to 15.

# 🟡 Intermediate Level
6️⃣ Create an array from 5 to 50 with step size 5.

7️⃣ Create a 4×4 identity matrix.

8️⃣ Create an array of 10 evenly spaced numbers between 1 and 100.

9️⃣ Create a 3×3 matrix filled with number 9.

🔟 Create an array of random integers between 1 and 20 (size = 5).

1️⃣1️⃣ Create a 2D array with shape (2, 3) using numbers from 1 to 6.

1️⃣2️⃣ Convert a Python list [10, 20, 30, 40] into a NumPy array.

# 🔴 Advanced / Interview Level
1️⃣3️⃣ Create a 3D array with shape (2, 2, 2).

1️⃣4️⃣ Create an empty array of shape (3, 3).

1️⃣5️⃣ Create an array using np.arange() and reshape it into a 3×3 matrix.

1️⃣6️⃣ What is the difference between np.zeros() and np.empty()?

1️⃣7️⃣ Create a boolean array with values: True, False, True, False.