# Create Array

# 🟢 1D Array Questions

1️⃣ Create a 1D array with elements: 5, 10, 15, 20.

2️⃣ Create an array with negative numbers: -1, -2, -3, -4.

3️⃣ Create a float array: 1.5, 2.5, 3.5, 4.5.

4️⃣ Create a boolean array: True, False, True, False.

5️⃣ Create an array with mixed integers: 100, 200, 300, 400, 500.

In [2]:
import numpy as np

In [3]:
arr1 = np.array([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [4]:
arr2 = np.array([-1, -2, -3, -4])
arr2

array([-1, -2, -3, -4])

In [5]:
arr3  = np.array([1.5, 2.5, 3.5, 4.5])
arr3

array([1.5, 2.5, 3.5, 4.5])

In [6]:
arr4 = np.array([True, False, True, False])
arr4

array([ True, False,  True, False])

In [7]:
arr5 = np.array([100, 200, 300, 400, 500])
arr5

array([100, 200, 300, 400, 500])

# 2D Array Questions
6️⃣ Create a 2×2 matrix:
- `[[1,2],
    [3,4]]`

7️⃣ Create a 3×3 matrix:
- `[[1,2,3],
    [4,5,6],
    [7,8,9]]`

8️⃣ Create a 2×3 matrix:
- `[[10,20,30],
    [40,50,60]]`

9️⃣ Create a 3×2 matrix:
- `[[1,2],
    [3,4],
    [5,6]]`

🔟 Create a matrix with all elements 7 (3 rows, 3 columns).

In [8]:
arr6 = np.array(([1, 2],
                 [3, 4]))
arr6

array([[1, 2],
       [3, 4]])

In [9]:
arr7 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr8 = np.array([[10, 20, 30],
                [40, 50, 60]])
arr8

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
arr9 = np.array([[1, 2],
                [3, 4],
                [5, 6]])
arr9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr10 = np.array([[7, 7, 7,],
                  [7, 7, 7],
                  [7, 7, 7]])
arr10

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [13]:
a = np.array([[2, 3],
              [4, 5]])

b = np.array([[1, 2],
              [3, 4]])

In [14]:
a * b

array([[ 2,  6],
       [12, 20]])

In [15]:
a @ b

array([[11, 16],
       [19, 28]])

In [18]:
a.dot(b)

array([[11, 16],
       [19, 28]])