In [2]:
import numpy as np

Array Attributes (20 Questions)

1. Print ndim of 1D array.

2. Print ndim of 2D array.

3. Print shape of 3×4 matrix.

4. Print size of array 1–20.

5. Print dtype of float array.

In [6]:
arr_1 = np.arange(1, 11)
print(arr_1.ndim)

1


In [ ]:
arr_2 = np.arange(1, 9).reshape(2, 4)
print(arr_2.ndim)

2

In [26]:
np.random.seed(42)
arr_3 = np.random.randint(1, 9, size=(3, 4))
print(arr_3.shape)

(3, 4)


In [6]:
arr_4 = np.arange(1, 21)
print(arr_4)
arr_4.size

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


20

In [7]:
arr_5 = np.arange(1, 10, dtype=float)
arr_5

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

6. Change dtype int → float.

7. Print itemsize of int32 array.

8. Check memory size of array.

9. Compare size of two arrays.

10. Create 3D array and print ndim.

In [10]:
arr_6 = np.arange(0, 6)
change_float = arr_6.astype(float)
change_float
print(change_float.dtype)


float64


In [11]:
arr_7 = np.array([1, 2, 3, 4], dtype=np.int32)
arr_7.itemsize

4

11. Create 3D array and print ndim.

12. Print shape after reshape.

13. Print size before reshape.

14. Print dtype after type conversion.

15. Create mixed type array and check dtype.

In [5]:
arr = np.arange(1, 13).reshape(2,2,3)
print(arr.ndim)
print(arr.size)


3
12


16. Print total elements in 4×5 matrix.

17. Print shape of empty array.

18. Print attributes of identity matrix.

19. Print attributes of random matrix.

20. Convert float array to int and check dtype.

21. Check if two arrays have same shape.

# Indexing & Slicing (20 Questions)

1. Print first element of array.

2. Print last element using negative index.

3. Print 3rd element.

4. Print first 5 elements.

5. Print last 3 elements.

In [15]:
arr_1 = np.array([1, 2, 3, 4, 5])
print("Fisrt_Element:- ", arr_1[0])

Fisrt_Element:-  1


In [17]:
arr_2 = np.array([10, 20, 30, 40, 50])
print("Last_element:- ", arr_2[-1])

Last_element:-  50


In [ ]:
arr_3 = np.array([10, 20, 30, 40, 50, 45, 56, 66])
print("3rd element:- ", arr_3[2])

3rd element:-  30


In [29]:
arr_4 = np.array([10, 30, 45, 56, 66, 45, 56, 66])
print("First to 3rd Element:- ", arr_4[:5])

First to 3rd Element:-  [10 30 45 56 66]


In [28]:
arr_5 = arr_4 = np.array([10, 30, 45, 56, 66, 45, 56, 66])
print("Last 3rd Element:- ", arr_4[-3:])

Last 3rd Element:-  [45 56 66]


6. Print elements from index 2–8.

7. Print every second element.

8. Reverse array using slicing.

9. Print alternate elements in reverse.

10. Extract row 2 from 3×3 matrix.

In [35]:
arr_6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_6[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
arr_7 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_7[0::2]

array([1, 3, 5, 7, 9])

In [36]:
arr_8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_8[::-1]
print("Reversed array: ", arr_8[::-1])

Reversed array:  [10  9  8  7  6  5  4  3  2  1]


In [40]:
arr_9 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_9[:-3][::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [45]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("1D array:- ", matrix[2])
print("2D array:- ", matrix[1:2, :])

1D array:-  [7 8 9]
2D array:-  [[4 5 6]]


11. Extract column 1 from matrix.

12. Print diagonal elements.

13. Print center element of 3×3 matrix.

14. Replace element at index 2 with 100.

15. Replace slice 1:4 with 0.

In [48]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

16. Select elements greater than 5.

17. Select even numbers only.

18. Select odd numbers only.

19. Modify first row of matrix.

20. Modify last column of matrix.

# Mathematical Operations

1. Add two arrays.

2. Subtract two arrays.

3. Multiply two arrays.

4. Divide two arrays.

5. Find square of array.

6. Find cube of array.

7. Find square root.

8. Find exponential values.

9. Find log values.

10. Find sum of array.

11. Find mean of array.

12. Find median.

13. Find standard deviation.

14. Find variance.

15. Find min value.

16. Find max value.

17. Find cumulative sum.

18. Find cumulative product.

19. Find row-wise sum of matrix.

20. Find column-wise mean.

# Broadcasting

1. Add 10 to array.

2. Multiply array by 5.

3. Subtract scalar from matrix.

4. Add vector to each row.

5. Add vector to each column.

6. Multiply column by 2.

7. Multiply 2×3 matrix with 1D array.

8. Divide matrix by scalar.

9. Add 1 to all diagonal elements.

10. Subtract row mean from each row.

11. Compare two arrays element-wise.

12. Create boolean mask >10.

13. Replace values >10 with 0.

14. Normalize array using broadcasting.

15. Standardize array (mean=0).

16. Add array of shape (3,) to (3,3).

17. Multiply (2,1) with (2,3).

18. Subtract column mean.

19. Add row sum to each row.

20. Apply operation without loop.

# Reshape & Manipulation

1. Reshape 1–12 into 3×4.

2. Reshape 1–16 into 4×4.

3. Convert 2D → 1D using ravel().

4. Convert 2D → 1D using flatten().

5. Insert value at index 2.

6. Delete value at index 3.

7. Append value at end.

8. Concatenate two arrays.

9. Vertically stack two arrays.

10. Horizontally stack two arrays.

11. Split array into 2 parts.

12. Split array into 4 equal parts.

13. Transpose matrix.

14. Change shape without changing data.

15. Swap rows.

16. Swap columns.

17. Resize array to new shape.

18. Flatten 3D array.

19. Reshape 2D to 3D.

20. Check difference between ravel & flatten.