In [1]:
import numpy as np

1. Create a NumPy array with 5 elements and insert 2 np.nan values.

2. Write code to check which elements are missing.

3. Count total missing values in this array:
[5, np.nan, 8, np.nan, 10]

4. Print only non-missing values from an array.

5. Replace all np.nan values with 0.

In [6]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
arr[0] = np.nan
arr[2] = np.nan
arr


array([nan,  2., nan,  4.,  5.])

In [11]:
# True means missing value found.
arr_2 = np.array([10, 20, np.nan, 40, 50, np.nan])
result = np.isnan(arr_2)
result

array([False, False,  True, False, False,  True])

In [16]:
arr_3 = np.array([5, np.nan, 8, np.nan, 10], dtype=float)
result = (np.sum(np.isnan(arr)))
result

np.int64(2)

In [18]:
arr_4 = np.array([5, np.nan, 8, np.nan, 10], dtype=float)
result = arr_4[~np.isnan(arr_4)]
result

array([ 5.,  8., 10.])

In [24]:
arr_5 = np.array([5, np.nan, 8, np.nan, 10], dtype=float)
arr_5[np.isnan(arr_5)] = 0
arr_5

array([ 5.,  0.,  8.,  0., 10.])

In [25]:
arr = np.array([5, np.nan, 8, np.nan, 10], dtype=float)

# Get indices of NaN values
nan_index = np.where(np.isnan(arr))[0]

# Replace first NaN with 99
arr[nan_index[0]] = 99

# Replace second NaN with 25
arr[nan_index[1]] = 25

print(arr)

[ 5. 99.  8. 25. 10.]


6. Find the mean of [10, 20, np.nan, 40] ignoring missing values.

7. Replace missing values with the mean of the array.

8. Remove all missing values and store result in a new array.

9. Find the index positions of missing values.

10. Use np.nansum() to calculate sum of [2, np.nan, 6, 8].

In [ ]:
arr

What happens if you use np.mean() on an array containing np.nan? Show example.

What happens if all values are np.nan and you use np.nanmean()?

Can an integer array store np.nan? Show example and explain.

Write a program to:

Count missing values

Replace them with median

Replace missing values with maximum value of the array.

Create a 2D array with missing values and count missing values row-wise.

Replace missing values column-wise with column mean.

Remove rows that contain at least one np.nan.

Remove columns that contain np.nan.

Write a full data cleaning program that:

Detects missing values

Counts them

Replaces with mean

Prints original and cleaned array