In [2]:
import numpy as np

In [4]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.arange(5, 51, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [9]:
arr_1 = np.arange(0, 1.1, 0.1)
arr_1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
arr_2 = np.linspace(1, 20, 5)
arr_2

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [14]:
arr_3 = np.arange(1, 16)
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

arange + reshpe

In [22]:
arr_4 = np.arange(1, 17).reshape(4, 4)
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
arr_5 = np.empty(5)
arr_5

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [24]:
arr_6 = np.array([1, 2, 3, 4], dtype=float)
arr_6

array([1., 2., 3., 4.])

In [26]:
List = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
List

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr_7 = ([True, False, True])
arr_7

[True, False, True]

In [29]:
arr_8 =np.array((1, 2, 3), dtype=complex)
arr_8

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
arr_9 = np.array((1, 2, 3, 4, 5))
arr_9

array([1, 2, 3, 4, 5])

In [38]:
# Create array of even numbers from 2–20
arr = np.arange(0, 21, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
arr = np.arange(1, 20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
arr_10 = np.full((5, 2), 8)
arr_10

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

In [44]:
arr = np.arange(10, 0, -1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [45]:
arr = np.arange(-5, 5)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [56]:
np.random.seed(42)
arr = np.random.randint(1, 11, (1, 10))
arr

array([[ 7,  4,  8,  5,  7, 10,  3,  7,  8,  5]], dtype=int32)

In [57]:
arr = np.arange(1, 9).reshape(2, 2, 2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])