1. An array has shape `(5,)`. What is its `ndim`?

2. An array has shape `(4, 6)`. What is its `size`?

3. An array has shape `(3, 4, 2)`. What is its `ndim`?

4. An array has 20 elements and shape `(4, 5)`. Is it 2D or 3D?

5. An array has `dtype = int32`. What is its `itemsize`?

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,])
arr.shape

(5,)

In [6]:
arr.ndim

1

In [34]:
arr_1 = np.arange(1, 25).reshape(4, 6)
arr_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [15]:
arr_1.shape

(4, 6)

In [14]:
arr_1.size

24

In [26]:
arr_2 = np.arange(1, 25).reshape(3, 4, 2)
print("Array:\n",arr_2)

Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [27]:
print("shape:\n",arr_2.shape)
print("ndim:\n",arr_2.ndim)

shape:
 (3, 4, 2)
ndim:
 3


In [28]:
arr_3 = np.arange(1, 21).reshape(4, 5)
arr_3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
arr_3.shape

(4, 5)

In [35]:
arr_4 = np.arange(1, 21).reshape(2, 5, 2)
arr_4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [39]:
arr_4.ndim

3

In [ ]:
arr_4.shape

(2, 5, 2)

In [44]:
# An array has 12 elements and shape (3, 4).Is it 2D or 3D?
arr = np.arange(1, 13).reshape(3, 4)
print("array:\n",arr)
print("shape: ",arr.shape)
print("Ndim: ",arr.ndim)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape:  (3, 4)
Ndim:  2


In [46]:
arr = np.arange(1, 13).reshape(1, 6, 2)
print("array:\n",arr)
print("shape: ",arr.shape)
print("Ndim: ",arr.ndim)

array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]
shape:  (1, 6, 2)
Ndim:  3


6. An array has `dtype = float64`. What is its `itemsize`?

7. An array has shape `(2, 3, 4)`. What is its `size`?

8. An array has shape `(10,)`. What is its `ndim`?

9. An array has shape `(1, 5)`. What is its `ndim`?

10. An array has shape `(5, 1)` What is its `ndim`?

In [48]:
arr_6 = np.arange(1, 25).reshape(2, 3, 4)
print("array:\n",arr_6)
print("shape: ",arr_6.shape)
print("Ndim: ",arr_6.ndim)

array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape:  (2, 3, 4)
Ndim:  3


In [49]:
arr_6 = np.arange(1, 6).reshape(5, 1)
print("array:\n",arr_6)
print("shape: ",arr_6.shape)
print("Ndim: ",arr_6.ndim)

array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
shape:  (5, 1)
Ndim:  2


11. An array has `dtype = int16`. What is its `itemsize`?

12. An array has shape `(2, 2, 2)`. What is its `size`?

13. An array has shape `(3, 3)`. What is its `size`?

14. An array has shape `(4, 1, 3)`. What is its `ndim`?

15. An array has shape `(6,)`. Is it 1D or 2D?

16. An array has shape `(2, 5, 5)`. What is its `ndim`?

17. An array contains 100 elements and is 1D. What is its shape?

18. An array has shape `(8, 2)` What is its total number of elements?

19. An array has shape `(3, 3, 3)`. What is its `size`?

20. An array has `dtype = float32`. What is its `itemsize`?

21. An array has shape `(7, 1, 1)`. What is its `ndim`?

22. An array has shape `(2, 4)`. After reshaping to `(4, 2)`, does ndim change?

23. An array has shape `(5, 5, 5, 5)`. What is its `ndim`?

24. An array has shape `(9,)`. What is its `size`?

25. An array has shape `(3, 2)`. What is its `ndim`?

26. An array has shape `(4, 4, 1)`. What is its `size`?

27. An array has 36 elements and is 2D with equal rows and columns. What is its shape?

28. An array has shape `(2, 3, 4, 5)`. What is its `ndim`?

29. An array has shape `(1,)`. What is its `ndim`?

30. An array has shape `(10, 10)`. What is its `size`?