🔹 1️⃣ Basic Random (0 to 1)

1. Create a 1D random array of 5 elements between 0 and 1.

2. Create a 3x3 random array between 0 and 1.

3. Set random seed to 10 and generate a 2x2 random array.

4. Generate a 4x4 random array and round values to 2 decimal places.

In [1]:
import numpy as np
arr = np.random.rand(5)
arr


array([0.50369303, 0.96213113, 0.25302238, 0.92206819, 0.59814918])

In [2]:
arr = np.random.rand(3,3)
arr

array([[0.54240978, 0.18950022, 0.36984477],
       [0.53059411, 0.72262295, 0.61382698],
       [0.43040562, 0.10142143, 0.67751838]])

In [4]:
np.random.seed(10)
arr = np.random.rand(2, 2)
arr

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388]])

In [ ]:
arr = np.random.rand(4, 4)
arr_round = np.round(arr, 2)
arr_round



array([[0.5 , 0.22, 0.2 , 0.76],
       [0.17, 0.09, 0.69, 0.95],
       [0.  , 0.51, 0.81, 0.61],
       [0.72, 0.29, 0.92, 0.71]])

🔹 2️⃣ Random Integers

5. Create a random integer array from 1 to 10 of size 5.

6. Create a 3x3 random integer matrix from 10 to 50.

7. Generate 6 random integers between -5 and 5.

8. Create a 2x4 matrix with random integers from 100 to 200.

In [37]:
arr = np.random.randint(1, 10, size=5)
arr

array([7, 9, 5, 3, 2], dtype=int32)

In [39]:
arr1 = np.random.randint(10, 50, size=(3, 2))
arr1

array([[44, 42],
       [40, 32],
       [15, 28]], dtype=int32)

In [43]:
arr2 = np.random.randint(-5, 5, size=6)
arr2

array([ 1,  4, -5, -1,  1, -1], dtype=int32)

In [44]:
arr3 = np.random.randint(100, 200, size=(2, 4))
arr3

array([[109, 140, 116, 175],
       [139, 158, 181, 139]], dtype=int32)

Generate 8 random integers between 1 and 20 and print only even numbers.

In [48]:
arr4 = np.random.randint(1, 20, size=8)
print("Original array:", arr4)

print()
even = arr4[arr4 % 2 == 0]
print("Even numbers:", even)

Original array: [ 4 17 12 10 19 10 18 11]

Even numbers: [ 4 12 10 10 18]


In [54]:
arr5 = np.random.randint(1, 10, size = 6)
print("Array:", arr5)
count = np.sum(arr5 > 5)
print("Numbers greater than 5:", count)

Array: [6 9 1 6 4 7]
Numbers greater than 5: 4


In [57]:
np.random.seed(42)
arr6 = np.random.randint(0, 5, size = (2, 3))
arr6

array([[3, 4, 2],
       [4, 4, 1]], dtype=int32)

In [59]:
np.random.seed()
arr7 = np.random.randint(1, 50, size=10)
print(arr7)
sort = np.sort(arr7)
sort

[33 15 12 22  3 41 43 37 30 32]


array([ 3, 12, 15, 22, 30, 32, 33, 37, 41, 43], dtype=int32)

🔹 3️⃣ Random Choice

9. Randomly select 5 elements from [10, 20, 30, 40, 50].

10. Randomly select 3 elements without replacement from `[1,2,3,4,5]`.

11. Generate a 2x3 array by randomly choosing from `[0,1]`.

12. Generate 10 random values from `['A','B','C']`.

In [20]:
arr = np.random.choice(['A', 'B', 'c'], size=10)
arr

array(['B', 'c', 'c', 'B', 'c', 'c', 'A', 'A', 'A', 'A'], dtype='<U1')

In [19]:
arr = np.random.choice([0, 1], size=(2, 3))
arr

array([[0, 0, 0],
       [1, 1, 0]])

In [ ]:
arr = np.random.choice([10, 20, 30, 40, 50], size=3, )
arr

array([20, 20, 50])

In [13]:
arr = np.random.choice([10, 20, 30, 40], 5, p=[0.1, 0.2, 0.3, 0.4])
arr

array([30, 10, 30, 20, 40])

In [18]:
arr = np.random.choice([1,2,3,4,5], size = 3, replace=False)
arr

array([2, 4, 3])

13. Generate 5 random elements from `[10, 20, 30, 40]`.

In [23]:
arr = np.random.choice([10, 30, 40, 30], size=5)
arr

array([30, 30, 40, 30, 10])

In [25]:
arr1 = np.random.choice(['A', 'B', 'C', 'D'], size = 3, replace=False)
arr1

array(['A', 'C', 'D'], dtype='<U1')

In [26]:
arr = np.random.choice([1, 2, 3, 4, 5], size=10)
arr

array([1, 3, 4, 1, 5, 3, 1, 4, 4, 2])

In [28]:
arr2 = np.random.choice([0, 1], size=(2, 3))
arr2

array([[1, 0, 1],
       [1, 0, 1]])

In [31]:
arr4 = np.random.choice(['X', 'Y', 'Z'], size=5, p=[0.1, 0.3, 0.6])
arr4

array(['X', 'Y', 'Y', 'Z', 'Z'], dtype='<U1')

In [33]:
arr = np.random.choice([1, 2, 3, 4, 5], size=10, replace=True)
arr

array([1, 1, 2, 1, 4, 4, 3, 1, 1, 5])

In [35]:
arr = np.random.choice([0, 1, 2], size=(3,3))
arr

array([[1, 1, 0],
       [2, 0, 1],
       [2, 0, 1]])

In [36]:
ap = np.random.choice(['Red', 'Blue', 'Green', 'Yellow'], size= 4, replace=True)
ap


array(['Red', 'Red', 'Red', 'Green'], dtype='<U6')